# Generated by Django 5.1.2 on 2024-11-14 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Phone',
        ),
        migrations.DeleteModel(
            name='PhoneImage',
        ),
    ]
