# Generated by Django 5.1.2 on 2024-11-14 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='description',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='images',
        ),
    ]
