# Generated by Django 5.1.2 on 2024-11-15 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_phone_options_phone_antiwater_phone_backcamera_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
