# Generated by Django 5.1.2 on 2024-11-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_review_alter_phone_refreshrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='price',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
