# Generated by Django 5.1.2 on 2024-11-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_phone_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='discount',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='phone',
            name='final_price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, null=True),
        ),
    ]
