# Generated by Django 5.1.2 on 2024-11-16 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_phone_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phone',
            options={},
        ),
        migrations.RemoveField(
            model_name='phone',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='final_price',
        ),
    ]
