# Generated by Django 5.1.2 on 2024-11-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_phone_options_remove_phone_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='price',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
