# Generated by Django 5.1.2 on 2024-11-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_remove_phone_discount_remove_phone_final_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='discount',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='phone',
            name='final_price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
