# Generated by Django 5.1.2 on 2024-11-16 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_phone_discount_alter_phone_final_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='final_price',
            new_name='FinalPrice',
        ),
    ]
