# Generated by Django 5.1.2 on 2024-11-16 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_rename_final_price_phone_finalprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.review'),
        ),
    ]
