# Generated by Django 5.1.2 on 2024-11-18 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_phone_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='ChargingPort',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
