# Generated by Django 5.1.2 on 2024-11-18 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_phone_chargingport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='RefreshRate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
