# Generated by Django 5.1.2 on 2024-11-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_tablet_tabletimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
