# Generated by Django 5.1.2 on 2024-11-21 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_alter_phone_otherfeatures_alter_tablet_otherfeatures'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartWatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(default=0)),
                ('discount', models.PositiveIntegerField(default=0)),
                ('FinalPrice', models.PositiveIntegerField(editable=False, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('compatibility', models.CharField(blank=True, max_length=50, null=True)),
                ('FarsiSupport', models.BooleanField(default=False)),
                ('conversation', models.BooleanField(default=False)),
                ('BatteryEfficiency', models.CharField(blank=True, max_length=100, null=True)),
                ('UserGroup', models.CharField(blank=True, max_length=50, null=True)),
                ('DimensionsWeights', models.CharField(blank=True, max_length=100, null=True)),
                ('BodyMaterial', models.CharField(blank=True, max_length=50, null=True)),
                ('Sensors', models.CharField(blank=True, max_length=150, null=True)),
                ('resistance', models.CharField(blank=True, max_length=100, null=True)),
                ('ReplaceStrap', models.BooleanField(default=False)),
                ('StrapMaterial', models.CharField(blank=True, max_length=50, null=True)),
                ('WatchFace', models.BooleanField(default=False)),
                ('speaker', models.BooleanField(default=False)),
                ('microphone', models.BooleanField(default=False)),
                ('StrapLock', models.CharField(blank=True, max_length=50, null=True)),
                ('ScreenType', models.CharField(blank=True, max_length=50, null=True)),
                ('resolution', models.CharField(blank=True, max_length=50, null=True)),
                ('ImageResolution', models.CharField(blank=True, max_length=50, null=True)),
                ('ScreenShape', models.CharField(blank=True, max_length=50, null=True)),
                ('ScreenSize', models.CharField(blank=True, max_length=50, null=True)),
                ('GPS', models.BooleanField(default=False)),
                ('bluetooth', models.CharField(blank=True, max_length=100, null=True)),
                ('BatteryCapacity', models.CharField(blank=True, max_length=100, null=True)),
                ('ChargingTime', models.CharField(blank=True, max_length=50, null=True)),
                ('OtherFeatures', models.CharField(blank=True, max_length=500, null=True)),
                ('OS', models.CharField(blank=True, max_length=100, null=True)),
                ('NFC', models.BooleanField(default=False)),
                ('WiFiNetwork', models.CharField(blank=True, max_length=100, null=True)),
                ('SIMCardSupport', models.BooleanField(default=False)),
                ('ChargingSource', models.CharField(blank=True, max_length=50, null=True)),
                ('vibration', models.BooleanField(default=False)),
                ('ProductID', models.CharField(blank=True, max_length=150, null=True)),
                ('cpu', models.CharField(blank=True, max_length=100, null=True)),
                ('InnerMemory', models.CharField(blank=True, max_length=50, null=True)),
                ('RAM', models.CharField(blank=True, max_length=50, null=True)),
                ('WatchStyle', models.CharField(blank=True, max_length=50, null=True)),
                ('LightOfScreen', models.CharField(blank=True, max_length=100, null=True)),
                ('ScreenOn', models.BooleanField(default=False)),
                ('SuitableFor', models.CharField(blank=True, max_length=50, null=True)),
                ('TypeOfMemoryCard', models.CharField(blank=True, max_length=50, null=True)),
                ('InstallSoftware', models.BooleanField(default=False)),
                ('IncludedItems', models.CharField(blank=True, max_length=100, null=True)),
                ('review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.review')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
