# Generated by Django 5.1.2 on 2024-11-21 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_smartwatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartWatchImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='smartwatch_images/')),
                ('smartwatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.smartwatch')),
            ],
        ),
    ]
