# Generated by Django 5.1.2 on 2024-11-21 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_smartwatchimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartwatch',
            name='IsFake',
            field=models.BooleanField(default=False),
        ),
    ]
