# Generated by Django 5.1.2 on 2024-11-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_accessory_producttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablet',
            name='InnerMemory',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='RAM',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
