# Generated by Django 5.1.2 on 2024-12-02 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_accessoryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='comparison',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.phone'),
        ),
        migrations.AlterField(
            model_name='accessoryimage',
            name='image',
            field=models.ImageField(upload_to='accessory_images/'),
        ),
    ]
