# Generated by Django 5.1.2 on 2024-12-02 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_phone_comparison_alter_accessoryimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='comparison',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.accessory'),
        ),
        migrations.AddField(
            model_name='airpods',
            name='comparison',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.airpods'),
        ),
        migrations.AddField(
            model_name='smartwatch',
            name='comparison',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.smartwatch'),
        ),
        migrations.AddField(
            model_name='tablet',
            name='comparison',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.tablet'),
        ),
    ]
