# Generated by Django 5.1.2 on 2024-12-07 14:33

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_accessory_comparison_airpods_comparison_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='review',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='text'),
        ),
        migrations.AlterField(
            model_name='smartwatch',
            name='review',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='text'),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='review',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='text'),
        ),
        migrations.AlterField(
            model_name='airpods',
            name='review',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='text'),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='review',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='text'),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
