# Generated by Django 5.1.2 on 2024-12-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_alter_phone_review_alter_smartwatch_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='CategoryName',
            field=models.CharField(default='accessory', max_length=30),
        ),
        migrations.AddField(
            model_name='airpods',
            name='CategoryName',
            field=models.CharField(default='airpod', max_length=30),
        ),
        migrations.AddField(
            model_name='phone',
            name='CategoryName',
            field=models.CharField(default='phone', max_length=30),
        ),
        migrations.AddField(
            model_name='smartwatch',
            name='CategoryName',
            field=models.CharField(default='smartwatch', max_length=30),
        ),
        migrations.AddField(
            model_name='tablet',
            name='CategoryName',
            field=models.CharField(default='tablet', max_length=30),
        ),
    ]
